# Generated by Django 5.0.6 on 2024-05-21 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='created_At',
            new_name='created_at',
        ),
    ]
